	create table agg_decision_audit_trail (
		id_acc NUMBER,
		id_usage_interval NUMBER,
		decision_unique_id VARCHAR2(400),
		parent_decision_unique_id VARCHAR2(400),
		decision_type VARCHAR2(4000),
		intervals_remaining NUMBER,
		start_date DATETIME,
		end_date DATETIME,
		expiration_date DATETIME,
		expired VARCHAR2(4000),
		audit_only VARCHAR2(4000),
		qualified_events NUMERIC(18,6),
		qualified_units NUMERIC(18,6),
		qualified_amount NUMERIC(18,6),
		total_generated_events NUMERIC(18,6),
		total_generated_amount NUMERIC(18,6),
		total_rated_events NUMERIC(18,6),
		total_rated_units NUMERIC(18,6),
		total_rated_amount_delta NUMERIC(18,6),
		total_rated_amount_after NUMERIC(18,6),
		total_discounted_events NUMERIC(18,6),
		total_discounted_units NUMERIC(18,6),
		total_discounted_amount NUMERIC(18,6),
		total_discount_amount NUMERIC(18,6),
		pre_qualified_events NUMERIC(18,6),
		pre_qualified_units NUMERIC(18,6),
		pre_qualified_amount NUMERIC(18,6),
		pre_total_generated_events NUMERIC(18,6),
		pre_total_generated_amount NUMERIC(18,6),
		pre_total_rated_events NUMERIC(18,6),
		pre_total_rated_units NUMERIC(18,6),
		pre_total_rated_amount_delta NUMERIC(18,6),
		pre_total_rated_amount_after NUMERIC(18,6),
		pre_total_discounted_events NUMERIC(18,6),
		pre_total_discounted_units NUMERIC(18,6),
		pre_total_discounted_amount NUMERIC(18,6),
		pre_total_discount_amount NUMERIC(18,6),
		CONSTRAINT agg_dec_audit_trail_pk PRIMARY KEY (id_acc, id_usage_interval, decision_unique_id) 
	);

